### ISSUE TITLE
Implementacja PPL

### ISSUE THREAD

**Issue by bartlomiej-szlachta** [bartlomiej-szlachta/heuristic-boat#5]
Czyli de facto metoda `evaluateOptimalBoatAngle`.

**Comment by bartlomiej-szlachta** [comment]
Algorytm powinien zwracać dwa dodatkowe klucze: `optimalAngle` oraz `optimalDistance`, zwracające pojedyncze wartości.

**Comment by bartlomiej-szlachta** [comment]
Rozważyłbym też zwracanie kątów w stopniach, a nie radianach - do przedyskutowania. Tak czy siak, niech nazwa klucza informuje o jednostce, w jakiej to jest zwracane

**Comment by bartlomiej-szlachta** [comment]
W jakich jednostkach jest wybierany Neighborhood factor? Rozmiar sąsiedztwa powinien być w tej samej jednostce, co zmienna funkcji celu, czyli na suwaku w stopniach

**Comment by kamil-rusin** [comment]
> W jakich jednostkach jest wybierany Neighborhood factor? Rozmiar sąsiedztwa powinien być w tej samej jednostce, co zmienna funkcji celu, czyli na suwaku w stopniach

Racja. Na ten moment są radiany. Poprawię to. Wtedy jaki limit ustalamy? Ile stopni? Bo np. jak bierzemy kąt 179 stopni i np. współczynnik sąsiedztwa (tak to nazwałem, chociaż niekoniecznie to jest to dokładnie) to po prostu margines dla losowania agentów, a jak ktoś wybierze 30 stopni to tak na prawdę losuje 149-179 mimo wszystko, bo 179 to limit :/  Ustawiłem na oko 5, ale na stopnie to można w sumie zmienić do 30 stopni? Czy nawet 90-ciu?

**Comment by bartlomiej-szlachta** [comment]
Hmm, jaki zakres, dobre pytanie. Na pewno minimum to 1 stopień, a maximum... 30 stopni jest gites, de facto daje to łącznie 60 stopni, bo po 30 w każdą stronę, więcej raczej nie trzeba.

Fakt, jeśli ktoś wybierze kąt inicjalny 175 stopni i rozmiar sąsiedztwa 30 stopni, to losowanie odbędzie się z przedziału 145-179 stopni. I gites, bo o to właśnie chodzi - nie możemy losować z innej dziedziny, niż dostępna.

**Comment by kamil-rusin** [comment]
Ok 😄

**Comment by bartlomiej-szlachta** [comment]
Widzę, że kąty są teraz zwracane jako string, na pewno nie ma możliwości zaokrąglenia do dwóch miejsc po przecinku pozostawiając typ float?

Poza tym myślę, że dystanse też by można było zaokrąglać analogicznie jak kąty

**Comment by bartlomiej-szlachta** [comment]
Ustawiłbym też inne domyślne wartości na suwakach, gdyż przy obecnie domyślnych wychodzi, że łódka może dopłynąć najbliżej na 4 metry (nie starcza iteracji na znalezienie lepszego kąta lub rozmiar sąsiedztwa jest zbyt mały - ja bym zwiększył domyślny rozmiar sąsiedztwa do 5-10 stopni)

**Comment by kamil-rusin** [comment]
Ok zmienię! Plus ilość iteracji ustawiłem losowo. Śmiało mogę większy limit dać.

**Comment by bartlomiej-szlachta** [comment]
Ilość iteracji myślę jest okej, tylko ten rozmiar sąsiedztwa niech będzie domyślnie większy 😉

**Comment by kamil-rusin** [comment]
Done.
